# This is a basic workflow to help you get started with Actions

name: firstCI

# Controls when the workflow will run
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: phpStan
        # You may pin to the exact commit or the version.
        # uses: NxtLvLSoftware/setup-phpstan-action@aa44652e7e9237f8f16f7a188a1c65cedb4d63b2
        uses: docker://oskarstark/phpstan-ga
        with:
          args: analyse .
